version: '3.8'

services:
  sing-box:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sing-box
    ports:
      - "443:443" 
    volumes:
     - ./config:/etc/sing-box/
    command: -D /var/lib/sing-box -C /etc/sing-box/ run
    restart: always
