# Use a lightweight base image
FROM ghcr.io/sagernet/sing-box

# Download and install sing-box

# Create configuration directory
RUN mkdir -p /etc/sing-box

# Copy the configuration file into the container

# Expose the default port
EXPOSE 443

# Command to run the application
#CMD ["sing-box", "run", "-c", "/etc/sing-box/config.json"]