services:
  sing-box:
    container_name: sing-box
    image: itdoginfo/sing-box:v1.10.7
    ports:
      - "8443:8443"
    environment:
      PROTOCOL: shadowsocks
      PASS: "F/mCnDGuOtmuqdWCIN6XsA=="
      SERVER: noski.sariy.ru
      #PUBLIC_KEY:
    restart: always
    # Enable for custom config (multiple accounts for example)
    volumes:
     - ./config:/etc/sing-box/
